### ISSUE TITLE
Improve performance of move contacts action

### ISSUE THREAD

**Issue by njogz** [medic/cht-conf#432]
**What feature do you want to improve?**
Moving contacts fails due to a large number of docs being loaded onto memory.

**Describe the improvement you'd like**
Refactor the move contacts action and particularly the section on moving reports by contacts

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by njogz** [comment]
Ready for AT [here](https://github.com/medic/cht-conf/pull/433/)

**Comment by ngaruko** [comment]
Tested using cht-conf on local against `clone-upgrade-muso-mali.dev`.

on master => throws errors :
```
 node src/bin/index.js --instance=clone-upgrade-muso-mali.dev  move-contacts -- --contacts=498e52d5b282433f88018c7ef4da67ee --parent=dc5112a5-52dc-4f55-954e-80928a7c2567
WARN Project has no dependency on cht-conf. 
🔑  Password: ********************************
INFO Checking that https://admin:****@clone-upgrade-muso-mali.dev.medicmobile.org/medic/ is available... 
WARN Attempting to use project for cht-conf against non-matching instance: https://admin:****@clone-upgrade-muso-mali.dev.medicmobile.org 
Are you sure? [y/n]: y
INFO Processing config in cht-conf. 
INFO Actions:
     - move-contacts 
INFO Starting action: move-contacts… 
ERROR FetchError: invalid json response body at https://clone-upgrade-muso-mali.dev.medicmobile.org/medic/_design/medic-client/_view/reports_by_freetext?include_docs=true reason: Cannot create a string longer than 0x1fffffe8 characters
    at /Users/bede/play/cht-conf/node_modules/pouchdb-adapter-http/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.reportsCreatedBy (/Users/bede/play/cht-conf/src/fn/move-contacts.js:218:21)
    at async updateLineagesAndStage (/Users/bede/play/cht-conf/src/fn/move-contacts.js:52:41)
    at async module.exports (/Users/bede/play/cht-conf/src/lib/main.js:214:5)
    at async /Users/bede/play/cht-conf/src/bin/index.js:11:18
```

On branch: Success
```
node src/bin/index.js --instance=clone-upgrade-muso-mali.dev  move-contacts -- --contacts=498e52d5b282433f88018c7ef4da67ee --parent=dc5112a5-52dc-4f55-954e-80928a7c2567
WARN Project has no dependency on cht-conf. 
🔑  Password: ********************************
INFO Checking that https://admin:****@clone-upgrade-muso-mali.dev.medicmobile.org/medic/ is available... 
WARN Attempting to use project for cht-conf against non-matching instance: https://admin:****@clone-upgrade-muso-mali.dev.medicmobile.org 
Are you sure? [y/n]: y
INFO Processing config in cht-conf. 
INFO Actions:
     - move-contacts 
INFO Starting action: move-contacts… 
INFO Processing 0 to 10000 report docs 
INFO Processing 10000 to 20000 report docs 
INFO Processing 20000 to 30000 report docs 
INFO Processing 30000 to 40000 report docs 
INFO Processing 40000 to 50000 report docs 
INFO Processing 50000 to 60000 report docs 
INFO Processing 60000 to 70000 report docs 
INFO Processing 70000 to 80000 report docs 
INFO Processing 80000 to 90000 report docs 
INFO Processing 90000 to 100000 report docs 
INFO Processing 100000 to 110000 report docs 
INFO Processing 110000 to 120000 report docs 
INFO Processing 120000 to 130000 report docs 
INFO Processing 130000 to 140000 report docs 
```
Since we have a feature to [warn when replicating too many docs](https://github.com/medic/cht-core/issues/5362), I wonder if we should do the same here, ie alert the configurer of how many docs (if a set limit has reached) they are about to move. Of course the warning above applies to users not contact, so if from a practical perspective, contacts are moved only for one user, ad not between users, then it shouldn't be an issue.
Your thought @njogz

**Comment by njogz** [comment]
@ngaruko that is a great suggestion but I think it should be a separate issue. I can create the issue if you agree it should be done separately from this one.

**Comment by ngaruko** [comment]
@njogz Certainly. We can merge this then!

**Comment by garethbowen** [comment]
@njogz The PR was merged so can we close the issue, or is there more to be done?
