### ISSUE TITLE
Cannot compile using medic-conf the app_settings

### ISSUE THREAD

**Issue by icm-marcelo** [medic/cht-conf#567]

**Comment by garethbowen** [comment]
@icm-marcelo Hi! It looks like you edited the issue and removed the details - can you provide any more information, such as error messages, or the config you're trying to compile?

**Comment by icm-marcelo** [comment]
Sorry for that, 

I have this kind of error that always showing when I will gonna push the updates to medic localhost.

INFO Processing config in flourish_vB0718. 
INFO Actions:
     - compile-app-settings
     - backup-app-settings
     - upload-app-settings
     - convert-app-forms
     - convert-collect-forms
     - convert-contact-forms
     - backup-all-forms
     - delete-all-forms
     - upload-app-forms
     - upload-collect-forms
     - upload-contact-forms
     - upload-resources
     - upload-custom-translations
     - upload-privacy-policies
INFO Starting action: compile-app-settings… 
INFO Packaging contact-summary 
INFO Hash: 9b99318ce61e1e529287
Version: webpack 4.46.0
Child
    Hash: 9b99318ce61e1e529287
    Time: 4734ms
    Built at: 07/20/2023 3:34:33 PM
                   Asset     Size  Chunks             Chunk Names
    ./contact-summary.js  129 KiB       0  [emitted]  main
    Entrypoint main = ./contact-summary.js
    [0] ./node_modules/luxon/build/cjs-browser/luxon.js 247 KiB {0} [built]
    [1] C:/Users/ICMFI-03/AppData/Roaming/npm/node_modules/medic-conf/src/contact-summary/lib.js 203 bytes {0} [built]
    [2] ./contact-summary.templated.js 34.3 KiB {0} [built]
    [3] ./contact-summary-extras.js 85.1 KiB {0} [built]
    [4] C:/Users/ICMFI-03/AppData/Roaming/npm/node_modules/medic-conf/src/contact-summary/contact-summary-emitter.js 3.29 KiB {0} [built]
INFO Packaging nools 
INFO Hash: a9a74f96553d317bd605
Version: webpack 4.46.0
Child
    Hash: a9a74f96553d317bd605
    Time: 2774ms
    Built at: 07/20/2023 3:34:36 PM
         Asset     Size  Chunks             Chunk Names
    ./nools.js  127 KiB       0  [emitted]  main
    Entrypoint main = ./nools.js
    [0] ./node_modules/luxon/build/cjs-browser/luxon.js 247 KiB {0} [built]
    [1] C:/Users/ICMFI-03/AppData/Roaming/npm/node_modules/medic-conf/src/nools/definition-preparation.js 1.36 KiB {0} [built]
    [2] C:/Users/ICMFI-03/AppData/Roaming/npm/node_modules/medic-conf/src/nools/lib.js 328 bytes {0} [built]
    [3] ./tasks.js 82.9 KiB {0} [built]
    [4] ./nools-extras.js 38.9 KiB {0} [built]
    [5] ./targets.js 20 bytes {0} [built]
    [6] C:/Users/ICMFI-03/AppData/Roaming/npm/node_modules/medic-conf/src/nools/task-emitter.js 4.73 KiB {0} [built]
    [7] C:/Users/ICMFI-03/AppData/Roaming/npm/node_modules/medic-conf/src/nools/target-emitter.js 2.75 KiB {0} [built]
INFO compile-app-settings complete. 
INFO Starting action: backup-app-settings… 
(node:10016) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use node --trace-warnings ... to show where the warning was created)
ERROR Error: Failed to fetch existing app_settings from https://medic:****@localhost/medic/_design/medic/_rewrite/app_settings/medic.
      Check that medic-api is running and that you're connecting on the correct port!
    at C:\Users\ICMFI-03\AppData\Roaming\npm\node_modules\medic-conf\src\lib\api.js:12:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (C:\Users\ICMFI-03\AppData\Roaming\npm\node_modules\medic-conf\src\lib\main.js:187:5)
    at async C:\Users\ICMFI-03\AppData\Roaming\npm\node_modules\medic-conf\src\bin\medic-conf.js:11:18
    


I've tried anything, even changing docker-compose file's port number, and still doesn't want to compile. I checked all the ports on my laptop and nothing was conflict with port 80, 443 and 5432.
