### ISSUE TITLE
Phython 2 is still needed to use xls2xform

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-conf#612]
**Describe the issue**
I use pyenv, if I have the 3.12.x (same version as originally installed in my macbook m3), and run `cht --local` in [default](https://github.com/medic/cht-core/tree/master/config/default) config. I get the following error:
```
INFO Error: There was a problem executing xls2xform.  It may not be installed.
E To install the latest pyxform, try one of the following:
E
E Ubuntu
E	sudo python -m pip install git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic
E OSX
E	pip install git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic
E Windows (as Administrator)
E	python -m pip install git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic --upgrade
    at /Users/jen/.nvm/versions/node/v20.10.0/lib/node_modules/cht-conf/src/lib/convert-forms.js:80:20
    at async execute (/Users/jen/.nvm/versions/node/v20.10.0/lib/node_modules/cht-conf/src/lib/convert-forms.js:60:5)
```

I tried installing the tool with pip3, but didn't work.
The error goes away whenever I switch to Phython 2.17

**Comment by latin-panda** [comment]
I've reset my computer setup and couldn't reproduce it anymore after some tries. Closing for now.
